name: "Build main"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-main:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#cadquery
    - run: nix flake check
